server:
  port: 8020

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://url:8020/database
    username: kimtaewoo
    password: kimtaewoo

logging:
  level:
    root: debug

