server:
  port: 8020

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: kimtaewoo
    password: kimtaewoo
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 100_000
      idleTimeout: 600000
      maximum-pool-size: 300
      minimum-idle: 5
      maxLifetime: 10000
      leak-detection-threshold: 2000

logging:
  level:
    root: debug

