version: "3"

services:
  board_postgres16_Blogger_You:
    image: postgres:16
    environment:
      POSTGRES_USER: kimtaewoo
      POSTGRES_DB: board
      POSTGRES_PASSWORD: kimtaewoo
      TZ: Asia/Seoul
    ports:
      - '5432:5432'
    restart: on-failure
    volumes:
      - sticky_volume_board_postgresql:/var/lib/postgresql/data
      - ./db/config/board:/docker-entrypoint-initdb.d/

  common_standalone_redis7_eelloo:
    image: redis:7.0
    ports:
      - 6379:6379
    volumes:
      - sticky_volume_common_redis:/redis/data
      - ./config/redis.conf:/usr/local/conf/redis.conf
    # 컨테이너에 docker label을 이용해서 메타데이터 추가
    labels:
      - "name=redis"
      - "mode=standalone"
    # 컨테이너 종료 시 재시작 여부 설정
    restart: on-failure

#volumes container
volumes:
  sticky_volumes_common_redis:
  sticky_volumes_board_postgredb:
