version: "3"

services:
  board_postgres_Blogger_You:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
    volumes:
      - sticky_volumes_board_postgresql:/var/lib/postgresql/data

  common_standalone_redis7:
    image: redis:7.0
    ports:
      - 6379:6379
    volumes:
      - sticky_volumes_common_redis:/redis/data
      - ./config/redis.conf:/usr/local/conf/redis.conf
    # 컨테이너에 docker label을 이용해서 메타데이터 추가
    labels:
      - "name=redis"
      - "mode=standalone"
    # 컨테이너 종료 시 재시작 여부 설정
    restart: on-failure

#volumes container
volumes:
  sticky_volumes_board_postgresql:
  sticky_volumes_common_redis:
